[build]
builder = "nixpacks"
buildCommand = "echo 'Dependencies managed by Nix'"

[deploy]
startCommand = "cd backend-deploy && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"