export interface WhiteLabelConfig {
  // Branding
  companyName: string;
  logoUrl?: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  
  // Domain and URLs
  domain: string;
  supportEmail: string;
  contactUrl?: string;
  
  // PDF Branding
  pdfHeaderText: string;
  pdfFooterText: string;
  pdfLogoUrl?: string;
  
  // Features
  showPoweredBy: boolean; // "Powered by InvestWise Pro"
  customFooter?: string;
  
  // Contact Information
  companyAddress?: string;
  phoneNumber?: string;
  website?: string;
}

export const DEFAULT_WHITELABEL_CONFIG: WhiteLabelConfig = {
  companyName: "InvestWise Pro",
  primaryColor: "#3B82F6", // blue-500
  secondaryColor: "#1E293B", // slate-800  
  accentColor: "#10B981", // emerald-500
  domain: "investwisepro.netlify.app",
  supportEmail: "support@investwisepro.com",
  pdfHeaderText: "InvestWise Pro ROI Analysis",
  pdfFooterText: "Generated by InvestWise Pro",
  showPoweredBy: false
};

// Example white label configs
export const EXAMPLE_WHITELABEL_CONFIGS: Record<string, WhiteLabelConfig> = {
  "smith-financial": {
    companyName: "Smith Financial Advisors",
    logoUrl: "/logos/smith-financial-logo.png",
    primaryColor: "#059669", // emerald-600
    secondaryColor: "#064E3B", // emerald-900
    accentColor: "#F59E0B", // amber-500
    domain: "calculator.smithfinancial.com",
    supportEmail: "support@smithfinancial.com",
    contactUrl: "https://smithfinancial.com/contact",
    pdfHeaderText: "Smith Financial Advisors - Investment ROI Analysis",
    pdfFooterText: "Smith Financial Advisors | Licensed Investment Advisor",
    pdfLogoUrl: "/logos/smith-financial-logo.png",
    showPoweredBy: true,
    companyAddress: "123 Finance Street, New York, NY 10001",
    phoneNumber: "(555) 123-4567",
    website: "https://smithfinancial.com"
  },
  
  "acme-consulting": {
    companyName: "ACME Business Consulting",
    logoUrl: "/logos/acme-logo.png", 
    primaryColor: "#DC2626", // red-600
    secondaryColor: "#7F1D1D", // red-900
    accentColor: "#F97316", // orange-500
    domain: "roi.acmeconsulting.com",
    supportEmail: "tools@acmeconsulting.com",
    pdfHeaderText: "ACME Business Consulting - ROI Calculator",
    pdfFooterText: "ACME Business Consulting | Strategic Business Solutions",
    showPoweredBy: true,
    website: "https://acmeconsulting.com"
  }
};