import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { WhiteLabelConfig, DEFAULT_WHITELABEL_CONFIG } from '../types/whitelabel';
import { apiClient } from '../utils/apiClient';

interface WhiteLabelContextType {
  config: WhiteLabelConfig;
  isWhiteLabel: boolean;
  isLoading: boolean;
  error: string | null;
  loadConfig: (clientId?: string, domain?: string) => Promise<void>;
  applyTheme: (config: WhiteLabelConfig) => void;
}

const WhiteLabelContext = createContext<WhiteLabelContextType | undefined>(undefined);

interface WhiteLabelProviderProps {
  children: ReactNode;
}

export const WhiteLabelProvider: React.FC<WhiteLabelProviderProps> = ({ children }) => {
  const [config, setConfig] = useState<WhiteLabelConfig>(DEFAULT_WHITELABEL_CONFIG);
  const [isWhiteLabel, setIsWhiteLabel] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const applyTheme = (newConfig: WhiteLabelConfig) => {
    // Apply CSS custom properties for theming
    const root = document.documentElement;
    root.style.setProperty('--wl-primary-color', newConfig.primaryColor);
    root.style.setProperty('--wl-secondary-color', newConfig.secondaryColor);
    root.style.setProperty('--wl-accent-color', newConfig.accentColor);
    
    // Apply advanced styling options
    if (newConfig.fontFamily) {
      root.style.setProperty('--wl-font-family', newConfig.fontFamily);
      document.body.style.fontFamily = newConfig.fontFamily;
    }
    
    // Update page title with personalized text
    const titleText = newConfig.calculatorTitle || 'ROI Calculator';
    document.title = `${newConfig.companyName} - ${titleText}`;
    
    // Update meta description
    const metaDescription = document.querySelector('meta[name="description"]') as HTMLMetaElement;
    if (metaDescription && newConfig.calculatorDescription) {
      metaDescription.content = newConfig.calculatorDescription;
    }
    
    // Update favicon if provided
    if (newConfig.logoUrl) {
      let favicon = document.querySelector('link[rel="icon"]') as HTMLLinkElement;
      if (!favicon) {
        favicon = document.createElement('link');
        favicon.rel = 'icon';
        document.head.appendChild(favicon);
      }
      favicon.href = newConfig.logoUrl;
      
      // Also update shortcut icon
      let shortcutIcon = document.querySelector('link[rel="shortcut icon"]') as HTMLLinkElement;
      if (!shortcutIcon) {
        shortcutIcon = document.createElement('link');
        shortcutIcon.rel = 'shortcut icon';
        document.head.appendChild(shortcutIcon);
      }
      shortcutIcon.href = newConfig.logoUrl;
    }
    
    // Apply custom CSS if provided
    if (newConfig.customCss) {
      let customStyleElement = document.querySelector('#white-label-custom-css') as HTMLStyleElement;
      if (!customStyleElement) {
        customStyleElement = document.createElement('style');
        customStyleElement.id = 'white-label-custom-css';
        document.head.appendChild(customStyleElement);
      }
      customStyleElement.textContent = newConfig.customCss;
    }
    
    setConfig(newConfig);
  };

  const loadConfig = async (clientId?: string, domain?: string) => {
    setIsLoading(true);
    setError(null);

    try {
      let response;
      
      if (clientId) {
        if (clientId === 'smith-financial' || clientId === 'acme-consulting') {
          response = await apiClient.getDemoWhiteLabelConfig(clientId);
        } else {
          response = await apiClient.getWhiteLabelConfig(clientId);
        }
      } else if (domain) {
        response = await apiClient.getWhiteLabelByDomain(domain);
      } else {
        const currentDomain = window.location.hostname;
        if (currentDomain !== 'localhost' && currentDomain !== 'investwisepro.netlify.app') {
          response = await apiClient.getWhiteLabelByDomain(currentDomain);
        }
      }

      if (response && response.success && response.data) {
        const data = response.data as any; // Type assertion for API response
        const whiteLabelConfig: WhiteLabelConfig = {
          companyName: data.company_name || data.companyName,
          logoUrl: data.logo_url || data.logoUrl,
          primaryColor: data.primary_color || data.primaryColor,
          secondaryColor: data.secondary_color || data.secondaryColor,
          accentColor: data.accent_color || data.accentColor,
          domain: data.custom_domain || data.subdomain || window.location.hostname,
          supportEmail: data.support_email || data.supportEmail,
          contactUrl: data.contact_url || data.contactUrl,
          pdfHeaderText: data.pdf_header_text || data.pdfHeaderText || `${data.company_name || data.companyName} - ROI Analysis`,
          pdfFooterText: data.pdf_footer_text || data.pdfFooterText || `Generated by ${data.company_name || data.companyName}`,
          pdfLogoUrl: data.pdf_logo_url || data.pdfLogoUrl,
          showPoweredBy: data.show_powered_by !== undefined ? data.show_powered_by : (data.showPoweredBy !== undefined ? data.showPoweredBy : true),
          customFooter: data.custom_footer || data.customFooter,
          companyAddress: data.company_address || data.companyAddress,
          phoneNumber: data.phone_number || data.phoneNumber,
          website: data.website,
          
          // Enhanced Personalization
          welcomeMessage: data.welcome_message || data.welcomeMessage,
          tagline: data.tagline,
          heroTitle: data.hero_title || data.heroTitle,
          heroSubtitle: data.hero_subtitle || data.heroSubtitle,
          ctaButtonText: data.cta_button_text || data.ctaButtonText,
          aboutText: data.about_text || data.aboutText,
          featuresText: data.features_text || data.featuresText,
          fontFamily: data.font_family || data.fontFamily,
          backgroundGradient: data.background_gradient || data.backgroundGradient,
          cardStyle: data.card_style || data.cardStyle || 'modern',
          buttonStyle: data.button_style || data.buttonStyle || 'rounded',
          calculatorTitle: data.calculator_title || data.calculatorTitle,
          calculatorDescription: data.calculator_description || data.calculatorDescription,
          socialLinks: data.social_links ? (typeof data.social_links === 'string' ? JSON.parse(data.social_links) : data.social_links) : undefined
        };

        applyTheme(whiteLabelConfig);
        setIsWhiteLabel(true);
      } else {
        // No white label config found, use default
        applyTheme(DEFAULT_WHITELABEL_CONFIG);
        setIsWhiteLabel(false);
      }
    } catch (err) {
      console.warn('Failed to load white label config:', err);
      // Fall back to default config
      applyTheme(DEFAULT_WHITELABEL_CONFIG);
      setIsWhiteLabel(false);
      setError('Failed to load branding configuration');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const clientId = urlParams.get('client') || urlParams.get('wl');
    
    const hostname = window.location.hostname;
    const isSubdomain = hostname.includes('.') && 
                       !hostname.startsWith('www.') && 
                       hostname !== 'investwisepro.netlify.app' &&
                       hostname !== 'localhost';

    if (clientId) {
      loadConfig(clientId);
    } else if (isSubdomain) {
      loadConfig(undefined, hostname);
    } else {
      applyTheme(DEFAULT_WHITELABEL_CONFIG);
    }
  }, []);

  const value: WhiteLabelContextType = {
    config,
    isWhiteLabel,
    isLoading,
    error,
    loadConfig,
    applyTheme
  };

  return (
    <WhiteLabelContext.Provider value={value}>
      {children}
    </WhiteLabelContext.Provider>
  );
};

export const useWhiteLabel = (): WhiteLabelContextType => {
  const context = useContext(WhiteLabelContext);
  if (context === undefined) {
    throw new Error('useWhiteLabel must be used within a WhiteLabelProvider');
  }
  return context;
};